### DISCUSSION TITLE
Backend storage

### DISCUSSION THREAD

**Discussion by ramazulay** [D10S0VSkY-OSS/Stack-Lifecycle-Deployment#90] [Ideas]
Hi @D10S0VSkY-OSS,
Do you have an ETA for "Support storage backend gcp cloud storage and azure blob storage"

Thanks.

**Comment by D10S0VSkY-OSS** [comment]
WIP

**Reply by D10S0VSkY-OSS** [reply]
Hi @ramazulay ,
new feature v2.10.0 now support azure blob storare, you need pass variables to sld-remote-state service:
```
SLD_STORE=azure
AZURE_STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=https;AccountName=<YOUR ACCOUNT>;AccountKey=<YOUR ACCESS KEY>;EndpointSuffix=core.windows.net"
```
See [azure-storage-configure-connection-string](https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string)

For play in kubernetes deploy need change storage-backend.yaml if use **pass secret in production **
```
apiVersion: apps/v1                                                                                                                      [20/2483]
kind: Deployment                                                                                                                                  
metadata:                                                                                                                                         
  name: remote-state                                                                                                                              
  labels:                                                                                                                                         
    name: remote-state                                                                                                                            
spec:                                                                                                                                             
  replicas: 1                                                                                                                                     
  selector:                                                                                                                                       
    matchLabels:                                                                                                                                  
      name: remote-state                                                                                                                          
  template:                                                                                                                                       
    metadata:                                                                                                                                     
      labels:                                                                                                                                     
        name: remote-state                                                                                                                        
    spec:                                                                                                                                         
      subdomain: primary                                                                                                                          
      containers:                                                                                                                                 
        - name: remote-state                                                                                                                      
          image: d10s0vsky/sld-remote-state:latest                                                                                                
          env:                                                                                                                                    
          - name: SLD_STORE
            value: azure
          - name: AZURE_STORAGE_CONNECTION_STRING
            value: "DefaultEndpointsProtocol=https;AccountName=<YOUR ACCOUNT>;AccountKey=<YOUR ACCESS KEY>;EndpointSuffix=core.windows.net"
          resources:


Regards

**Reply by D10S0VSkY-OSS** [reply]
Hi @ramazulay,
new feature v2.11.0 now support google cloud storage, you need pass variables to sld-remote-state service:
```
SLD_STORE=gcp
export GOOGLE_APPLICATION_CREDENTIALS="/app/sld-gcp-credentials.json"
```
See [Google Cloud authentication](https://cloud.google.com/docs/authentication/getting-started)

Set in kubernetes deployment using secret:

**Import google  service account key to  k8s secret**
```
kubectl create secret generic gcp-storage --from-file=~/Downloads/storage.json
```
**Modify sld-remote-state.yml set gcp storage cloud backend and mount secret:**
```
apiVersion: apps/v1                                                                                                                               
kind: Deployment                                                                                                                                  
metadata:                                                                                                                                         
  name: remote-state                                                                                                                              
  labels:                                                                                                                                         
    name: remote-state                                                                                                                            
spec:                                                                                                                                             
  replicas: 1                                                                                                                                     
  selector:                                                                                                                                       
    matchLabels:                                                                                                                                  
      name: remote-state         
  template:                                                                                                                                                                                                        
    metadata:                                                                  
      labels:                                                            
        name: remote-state                                               
    spec:                        
      subdomain: primary                                                                                                                                                                                                                                                        
      containers:                                                                              
        - name: remote-state                                                                   
          image: d10s0vsky/sld-remote-state:latest                                                                     
          volumeMounts:                    
          - name: gcp                                                                                                                                         
            mountPath: "/app/gcp"                                                                                                                                            
            readOnly: true                          
          env:                                      
          - name: SLD_STORE                         
            value: gcp                              
          - name: GOOGLE_APPLICATION_CREDENTIALS                                                                                                                                                                   
            value: "/app/gcp/storage.json"                                                                             
          resources:                                                
            limits:                                                 
              memory: 600Mi                                         
              cpu: 1                                                                                                                                                                                                                                                            
            requests:                                                          
              memory: 300Mi                                                    
              cpu: 500m                                                        
          imagePullPolicy: Always                                              
          command: ["python3", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--workers", "1"]                                          
          ports:                                                                               
            - containerPort: 8080                                                              
          livenessProbe:                                                                       
            httpGet:                                                                           
              path: /                                                                          
              port: 8080                                                                                                                                                                      
              httpHeaders:                                                                                             
              - name: status                                                                                           
                value: healthy                                                                                         
            initialDelaySeconds: 60                                                                                    
            periodSeconds: 60                                                                                          
      volumes:                                                                                                         
      - name: gcp                                                                                                      
        secret:                                                                                                        
          secretName: gcp-storage                                                    
```
